# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dreamai',
                'doc_host': 'https://HamzaFarhan.github.io',
                'git_url': 'https://github.com/HamzaFarhan/dreamai',
                'lib_path': 'dreamai'},
  'syms': {'dreamai.core': {'dreamai.core.foo': ('core.html#foo', 'dreamai/core.py')}}}
