name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install
      run: pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
    - name: Set the uses
      uses: fastai/workflows/quarto-ghp@master