name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set the uses
      uses: fastai/workflows/quarto-ghp@master
    - name: Install
      run: conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia